# Generated by Django 4.1.1 on 2022-10-03 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_unique_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('bus_class_type', models.CharField(max_length=10)),
                ('departure_city', models.CharField(max_length=10)),
                ('arrival_city', models.CharField(max_length=10)),
                ('date_of_departure', models.DateField()),
                ('time_of_departure', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('identification_number', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.bus')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.passenger')),
            ],
        ),
    ]
