# Generated by Django 4.1.1 on 2022-10-03 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bus',
        ),
        migrations.AddField(
            model_name='reservation',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_booked', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(35)])),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.bus')),
                ('reservations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_app.reservation')),
            ],
        ),
    ]
